<?php
// Courier Management System - Installer Step 5: Finish
// Created: 2026-08-08

require_once 'lock-check.php';

// On page load, automatically generate config and lock file
if (!isset($_SESSION['db_host']) || !isset($_SESSION['db_name']) || !isset($_SESSION['db_user'])) {
    header('Location: step2-database.php?error=session_expired');
    exit;
}

$host = $_SESSION['db_host'];
$port = $_SESSION['db_port'];
$dbname = $_SESSION['db_name'];
$username = $_SESSION['db_user'];
$password = $_SESSION['db_pass'];
$adminUsername = $_SESSION['admin_username'] ?? 'admin';

// Generate config.php
$configContent = "<?php
// Courier Management System - Configuration File
// Generated by installer on " . date('Y-m-d H:i:s') . "

// Site Configuration
define('SITE_NAME', 'Courier Management System');
define('BASE_URL', '/courier-mgt/');

// Database Configuration
define('DB_HOST', '" . addslashes($host) . "');
define('DB_PORT', '" . addslashes($port) . "');
define('DB_NAME', '" . addslashes($dbname) . "');
define('DB_USER', '" . addslashes($username) . "');
define('DB_PASS', '" . addslashes($password) . "');

// Session Configuration
ini_set('session.cookie_httponly', 1);
ini_set('session.use_only_cookies', 1);
ini_set('session.cookie_secure', 0); // Set to 1 if using HTTPS
session_name('CMS_SESSION');
session_start();

// Error Reporting (Set to 0 in production)
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);
ini_set('error_log', __DIR__ . '/../logs/error.log');

// Timezone
date_default_timezone_set('UTC');

// Timezone
date_default_timezone_set('UTC');
";

$configFile = __DIR__ . '/../config/config.php';
if (file_put_contents($configFile, $configContent) === false) {
    die('Failed to write config.php. Please check that the config folder is writable.');
}

// Create installed.lock file
$lockFile = __DIR__ . '/../config/installed.lock';
$lockContent = "Installation completed on " . date('Y-m-d H:i:s') . "\n";
file_put_contents($lockFile, $lockContent);

// Clear installer session variables
unset($_SESSION['db_host']);
unset($_SESSION['db_port']);
unset($_SESSION['db_name']);
unset($_SESSION['db_user']);
unset($_SESSION['db_pass']);
unset($_SESSION['admin_username']);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Courier Management System - Setup Wizard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link href="../assets/css/style.css" rel="stylesheet">
    <link href="assets/installer.css" rel="stylesheet">
</head>
<body class="installer-body">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="installer-card">
                    <div class="installer-header">
                        <h1><i class="fas fa-truck"></i> Courier Management System</h1>
                        <p class="text-muted">Setup Wizard</p>
                    </div>
                    
                    <!-- Step Progress -->
                    <div class="step-progress">
                        <div class="step step-completed" data-step="1">
                            <div class="step-number"><i class="fas fa-check"></i></div>
                            <div class="step-label">Welcome</div>
                        </div>
                        <div class="step step-completed" data-step="2">
                            <div class="step-number"><i class="fas fa-check"></i></div>
                            <div class="step-label">Database</div>
                        </div>
                        <div class="step step-completed" data-step="3">
                            <div class="step-number"><i class="fas fa-check"></i></div>
                            <div class="step-label">Import</div>
                        </div>
                        <div class="step step-completed" data-step="4">
                            <div class="step-number"><i class="fas fa-check"></i></div>
                            <div class="step-label">Admin</div>
                        </div>
                        <div class="step step-active" data-step="5">
                            <div class="step-number">5</div>
                            <div class="step-label">Finish</div>
                        </div>
                    </div>
                    
                    <div class="installer-body text-center">
                        <div class="success-icon">
                            <i class="fas fa-check-circle"></i>
                        </div>
                        <h2 class="mt-4">Installation Complete!</h2>
                        <p class="text-muted mb-4">
                            Your Courier Management System has been successfully installed and configured.
                        </p>
                        
                        <div class="alert alert-info">
                            <strong>Admin Account:</strong><br>
                            Username: <?php echo htmlspecialchars($adminUsername); ?><br>
                            <small class="text-muted">Your password was set in the previous step. Please keep it secure.</small>
                        </div>
                        
                        <div class="alert alert-warning">
                            <i class="fas fa-shield-alt"></i>
                            <strong>Security Notice:</strong><br>
                            For security reasons, we recommend removing the installer files from your server.
                        </div>
                    </div>
                    
                    <div class="installer-footer">
                        <a href="../auth/login.php" class="btn btn-primary">
                            <i class="fas fa-sign-in-alt"></i> Go to Login
                        </a>
                        <button type="button" id="cleanup-btn" class="btn btn-success">
                            <i class="fas fa-trash-alt"></i> Secure My Installation (Recommended)
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="assets/installer.js"></script>
</body>
</html>
